// Static catalog of every job discovery source the system knows about.
// activeWhen(ctx) determines whether the source fires for a given user profile.
// ctx shape: { wantsRemote, hasCanadian, hasUS, isTech, roles, adzunaKeySet }

const SOURCES_CATALOG = [
  // ── Always-on ──────────────────────────────────────────────────────────────
  {
    id: 'indeed',
    name: 'Indeed',
    description: 'Largest job board — location-based and remote searches',
    category: 'general',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: true,
    websiteUrl: 'https://indeed.com',
    logoEmoji: '🔍',
    activeWhen: () => true,
  },
  {
    id: 'remotive',
    name: 'Remotive',
    description: 'Curated remote jobs with a free JSON API',
    category: 'remote',
    type: 'json',
    free: true,
    requiresKey: false,
    alwaysOn: true,
    websiteUrl: 'https://remotive.com',
    logoEmoji: '🌍',
    activeWhen: () => true,
  },
  {
    id: 'themuse',
    name: 'The Muse',
    description: 'Job board with company culture data — free API, no key needed',
    category: 'general',
    type: 'json',
    free: true,
    requiresKey: false,
    alwaysOn: true,
    websiteUrl: 'https://themuse.com',
    logoEmoji: '💡',
    activeWhen: () => true,
  },
  // ── Remote-focused ─────────────────────────────────────────────────────────
  {
    id: 'indeed-remote',
    name: 'Indeed Remote',
    description: 'Remote-only Indeed searches per target role',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://indeed.com',
    logoEmoji: '🔍',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'remoteok',
    name: 'Remote OK',
    description: 'Remote tech and operations jobs RSS by category',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://remoteok.com',
    logoEmoji: '💻',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'weworkremotely',
    name: 'We Work Remotely',
    description: 'One of the largest dedicated remote job boards',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://weworkremotely.com',
    logoEmoji: '🏡',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'himalayas',
    name: 'Himalayas',
    description: 'Remote-first board with salary transparency',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://himalayas.app',
    logoEmoji: '🏔',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'remoteco',
    name: 'Remote.co',
    description: 'Curated remote listings across all job categories',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://remote.co',
    logoEmoji: '🌐',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'workingnomads',
    name: 'Working Nomads',
    description: 'Remote jobs for location-independent professionals',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://www.workingnomads.com',
    logoEmoji: '✈️',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'jobspresso',
    name: 'Jobspresso',
    description: 'Hand-curated remote roles in tech, marketing, and support',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://jobspresso.co',
    logoEmoji: '☕',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: '4dayweek',
    name: '4 Day Week',
    description: 'Remote-friendly jobs at companies with 4-day work weeks',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://4dayweek.io',
    logoEmoji: '📅',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  {
    id: 'nodesk',
    name: 'NoDesk',
    description: 'Curated remote job board and newsletter',
    category: 'remote',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://nodesk.co',
    logoEmoji: '🖥',
    inactiveReason: 'Enable remote in your profile to activate',
    activeWhen: ctx => ctx.wantsRemote,
  },
  // ── Canada-specific ─────────────────────────────────────────────────────────
  {
    id: 'jobbank',
    name: 'Job Bank Canada',
    description: 'Government of Canada official job board with RSS per role + city',
    category: 'canada',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://www.jobbank.gc.ca',
    logoEmoji: '🍁',
    inactiveReason: 'Add a Canadian city to your target locations to activate',
    activeWhen: ctx => ctx.hasCanadian,
  },
  // ── Tech-specific ───────────────────────────────────────────────────────────
  {
    id: 'dice',
    name: 'Dice',
    description: 'Tech-focused job board with role + location RSS feeds',
    category: 'tech',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://dice.com',
    logoEmoji: '🎲',
    inactiveReason: 'Add a tech role (engineer, developer, DevOps, etc.) to activate',
    activeWhen: ctx => ctx.isTech,
  },
  {
    id: 'builtin',
    name: 'Built In',
    description: 'Tech job board with city-specific RSS — NY, SF, Austin, Seattle, and more',
    category: 'tech',
    type: 'rss',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://builtin.com',
    logoEmoji: '🏙',
    inactiveReason: 'Add a supported US city (NY, SF, Austin, Seattle, Boston, Chicago, Denver, LA)',
    activeWhen: ctx => ctx.hasUS,
  },
  // ── Startup / community ────────────────────────────────────────────────────
  {
    id: 'hn-hiring',
    name: "HN: Who's Hiring",
    description: 'Monthly Hacker News thread — high signal for startup and tech roles. Runs once per month.',
    category: 'startup',
    type: 'hn',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://news.ycombinator.com',
    logoEmoji: '🦊',
    inactiveReason: 'Add at least one target role to your profile to activate',
    activeWhen: ctx => ctx.roles.length > 0,
  },
  // ── Requires API key ────────────────────────────────────────────────────────
  {
    id: 'adzuna',
    name: 'Adzuna',
    description: 'Aggregates millions of listings — free tier: 1000 API calls/month',
    category: 'general',
    type: 'json',
    free: true,
    requiresKey: true,
    alwaysOn: false,
    websiteUrl: 'https://developer.adzuna.com',
    logoEmoji: '📊',
    inactiveReason: 'Add ADZUNA_APP_ID + ADZUNA_APP_KEY to your server .env to activate',
    activeWhen: ctx => ctx.adzunaKeySet,
  },
  // ── Company ATS (user-configured via watched companies) ────────────────────
  {
    id: 'workday',
    name: 'Workday ATS',
    description: 'Scrape Workday career pages for large employers — add URLs to watched companies',
    category: 'company_ats',
    type: 'scrape',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://myworkdayjobs.com',
    logoEmoji: '🏢',
    inactiveReason: 'Add a Workday career page URL to watched companies',
    activeWhen: () => false,
  },
  {
    id: 'ashby',
    name: 'Ashby ATS',
    description: 'Scrape Ashby career pages (jobs.ashbyhq.com/{company}) via watched companies',
    category: 'company_ats',
    type: 'scrape',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://ashbyhq.com',
    logoEmoji: '🚀',
    inactiveReason: 'Add an Ashby career page URL to watched companies',
    activeWhen: () => false,
  },
  {
    id: 'smartrecruiters',
    name: 'SmartRecruiters',
    description: 'Scrape SmartRecruiters career pages via watched companies',
    category: 'company_ats',
    type: 'scrape',
    free: true,
    requiresKey: false,
    alwaysOn: false,
    websiteUrl: 'https://smartrecruiters.com',
    logoEmoji: '🎯',
    inactiveReason: 'Add a SmartRecruiters career page URL to watched companies',
    activeWhen: () => false,
  },
];

const TECH_KEYWORDS = ['engineer', 'developer', 'devops', 'sre', 'data', 'cloud', 'software', 'infrastructure', 'security', 'architect'];

function buildContext(profile) {
  const locations = profile.locations || [];
  const roles = profile.targetRoles || [];
  const wantsRemote = profile.openToRemote ||
    locations.some(l => l === 'remote' || l.startsWith('remote '));
  const hasCanadian = locations.some(l => l.endsWith(', Canada') || l === 'remote Canada');
  const hasUS = locations.some(l =>
    !l.startsWith('remote') && !l.includes('Canada') && !l.includes('Mexico') && l.includes(',')
  );
  const isTech = TECH_KEYWORDS.some(kw => roles.join(' ').toLowerCase().includes(kw));
  return { wantsRemote, hasCanadian, hasUS, isTech, roles, adzunaKeySet: !!process.env.ADZUNA_APP_ID };
}

// Returns all catalog entries with an `active` boolean based on the user's profile.
// The `activeWhen` function is stripped from each entry before returning.
function getActiveSources(profile) {
  const ctx = buildContext(profile || {});
  return SOURCES_CATALOG.map(({ activeWhen, ...src }) => ({
    ...src,
    active: activeWhen(ctx),
  }));
}

module.exports = { SOURCES_CATALOG, getActiveSources };
